BlogApp/urls.py
from django.urls import path
from BlogApp.views import ArticuloDeleteView, ArticuloDetailView, ArticuloListView, ArticuloUpdateView, about, action_buscar_articulo, buscar_articulos, crear_articulo, inicio, articulos

urlpatterns = [
    path('', inicio, name="inicio"),
    path('about', about, name="about"),
    path('crear-articulo', crear_articulo, name="crear-articulo"),
    path('buscar-articulos', buscar_articulos, name="buscar-articulos"),
    path('action-buscar-articulo', action_buscar_articulo, name="action-buscar-articulo"),  # type: ignore
    path('editar-articulo/<int:pk>/', ArticuloUpdateView.as_view(), name="editar-articulo"),
    path('listar-articulos', ArticuloListView.as_view(), name="listar-articulos"),
    path('detalle-articulo/<int:pk>/', ArticuloDetailView.as_view(), name="detalle-articulo"),
    path('eliminar-articulo/<int:pk>/', ArticuloDeleteView.as_view(), name="eliminar-articulo"),
] 

CodeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogApp.urls')),
    path('accounts/', include('Perfiles.urls')),
    path('messages/', include('Messages.urls')),
]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Messages/urls.py
from django.urls import path
from Messages.views import NewChatView, ChatList, detalle_chat, EliminarChat, new_message_view

urlpatterns = [
    path('newchat', NewChatView.as_view(), name="newchat"),
    path('chats', ChatList.as_view(), name="chats"),
    path('detalle-chat/<int:pk>', detalle_chat, name="detalle-chat"),  # type: ignore
    path('newmessage/<int:pk>', new_message_view, name="newmessage"),  # type: ignore
    path('eliminar-chat/<int:pk>', EliminarChat.as_view(), name="eliminar-chat"),
] 

Messages/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Chat(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='User1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name="User2", verbose_name='Usuario')

class Message(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=255, blank=True, verbose_name='Mensaje')
    chat_id = models.ForeignKey(Chat, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

Messages/forms.py
from django import forms
from Messages.models import Message
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']

Messages/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from Messages.forms import MessageForm
from Messages.models import Chat, Message

class NewChatView(LoginRequiredMixin, CreateView):
    model = Chat 
    fields= ['user2']
    success_url = reverse_lazy('chats')
    template_name= "newchat.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user1 = self.request.user
        self.object.save()        
        return HttpResponseRedirect(self.get_success_url())

class ChatList(LoginRequiredMixin, ListView):
    model = Chat 
    template_name= "chats.html"

@login_required  # type: ignore
def detalle_chat(request, pk):
    chat_identifier = Chat.objects.get(id=pk)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            mensaje = Message(text=data['text'], chat_id=chat_identifier, author=request.user)
            mensaje.save()
            return redirect(reverse('detalle-chat', kwargs={'pk':pk}))
    else:
        form = MessageForm()
        return render(request, 'detalle-chat.html', {"form": form, 'object': chat_identifier})

class EliminarChat(LoginRequiredMixin, DeleteView):
    model = Chat
    success_url = reverse_lazy('chats')
    template_name= "eliminar.html"

@login_required  # type: ignore
def new_message_view(request, pk):
    chat_identifier = Chat.objects.get(id=pk)

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            mensaje = Message(text=data['text'], chat_id=chat_identifier, author=request.user)
            mensaje.save()
            return redirect(reverse('detalle-chat', kwargs={'pk':pk}))
    else:
        form = MessageForm()
        return render(request, 'newmessage.html', {"form": form})

Messages/templates/chats.html
{% extends "BlogApp/base.html" %}

{% load static %}

{% block contenido_no_heredado %}   
<title>Chat</title>
<div style="margin: 5%" >

<div class="title">Mensajería</div>

    {% if mensaje %}
        <div class = "mensaje">
            {{mensaje}}
        </div>
    {% endif %}
    <p>Comience a chatear... </p>
    <ul class="lista">{% if object_list|length > 0 %}
        {% for chat in object_list %}
            {% if user.username == chat.user1.username or user.username == chat.user2.username %}
                <hr />
                <li><a href="{% url "detalle-chat" chat.id %}">
                    <h4>Chat con  {% if user.username == chat.user1.username %}{{chat.user2.username}}{% else %}{{chat.user1.username}} {% endif %}</h4><br>
                    
                    <img width="66px" src=
                    {% if user.username == chat.user1.username %}
                        {% if chat.user2.avatar.imagen %}"{{chat.user2.avatar.imagen.url}}"
                        {% else%}"{% static 'BlogApp/assets/img/noprofile.jpg' %}"
                        {% endif %}
                    {% else%}
                        {% if chat.user1.avatar.imagen %}"{{chat.user1.avatar.imagen.url}}"
                        {% else%}"{% static 'BlogApp/assets/img/noprofile.jpg' %}"
                        {% endif %}
                    {% endif %}
                    ><br></a><br>
                    <a class='btn btn-danger' href="{% url 'eliminar-chat' chat.id %}">Eliminar chat</a>
                    <br>
                    <br>
                </li>
            {% endif %}
        {% endfor %}
        {% endif %}
        <a class = "btn btn-success rounded" href="{% url 'newchat' %}">Nuevo chat</a>
    </ul>

</div>
    
<br><br>

{% endblock contenido_no_heredado %}   

Messages/templates/detalle-chat.html
{% extends "BlogApp/base.html" %}

{% load static %}

{% block contenido_no_heredado %}   
<title>Chat</title>
<div style="margin: 5%" >

<div class="title">Mensajería</div>

    {% if mensaje %}
        <div class = "mensaje">
            {{mensaje}}
        </div>
    {% endif %}

    <a class="btn btn-success" href="{% url 'chats' %}">Regresar</a>
    
    <ul class="lista">
        {% if object.message_set.all|length > 0%}
        {% for message in object.message_set.all %}
        <li>
            <p><img width="50px"  class="rounded-circle" src={% if message.author.avatar.imagen %}"{{message.author.avatar.imagen.url}}"{% else%}"{% static 'BlogApp/assets/img/noprofile.jpg' %}"{% endif %}>&nbsp; {{message.text}}</p><br>
            <i>{{message.created}}</i><br>
            <i>{{message.author}}</i><br>
        </li>
        {% endfor %}
        {% else %}
        <p>No hay mensajes...</p>
        {% endif %}

    </ul>
    <div class="form_bloque">
        <form class="form_estilo" method="POST">
            <div class="form_title">Nuevo Mensaje</div>
            <div class="atributos">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <input class="submit" type="submit"  value="Enviar">
        </form>
    </div>

</div>
    
<br><br>

{% endblock contenido_no_heredado %}   

Messages/templates/eliminar.html
{% extends "BlogApp/base.html" %}

{% load static %}

{% block contenido_no_heredado %}   
<br>
<br>
<br>
<div class="card m-3 p-3">Eliminando {{object.titulo}}</div>

    {% if mensaje %}
        <div class = "mensaje">
            {{mensaje}}
        </div>
    {% endif %}
<div class="bloque_forms">

    <div class="form_bloque">
        <form class="m-3 p-3 card"  method="POST" enctype="multipart/form-data">
            <p>¿Estás seguro de eliminar el chat con {% if user.username == object.user1.username %}{{object.user2.username}}{% else %}{{object.user1.username}} {% endif %}?</p>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Confirmar">
        </form>
    </div>
</div>


    
<br><br>

{% endblock contenido_no_heredado %}   

Messages/templates/newchat.html
{% extends "BlogApp/base.html" %}

{% load static %}

{% block contenido_no_heredado %}   
<title>Chat</title>
<div style="margin: 5%" >


<div class="title">Mensajería</div>

<a class="btn btn-success" href="{% url 'chats' %}">Regresar</a>

    {% if mensaje %}
        <div class = "mensaje">
            {{mensaje}}
        </div>
    {% endif %}
    
<div class="bloque_forms">
 
    <div class="form_bloque">
        <form class="form_estilo" method="POST">
            <div class="form_title">Nuevo Chat</div>
            <div class="atributos">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <input class="submit" type="submit"  value="Comenzar">
        </form>
    </div>

</div>

</div>
    
<br><br>

{% endblock contenido_no_heredado %}   